/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 6.5 */
/* Sat Apr  1 13:44:25 2017 */

/* parameterized module instance */
ram __ (.WrAddress( ), .RdAddress( ), .Data( ), .ByteEn( ), .WE( ), 
    .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), 
    .Q( ));
